#!/usr/bin/env python3
"""Emit the deterministic perf dataset, as SQL or as NDJSON.

Shape mirrors the round-22 production dataset (2026-06-12 forensics):
24 304 messages / 23 508 distinct threads / 6 263 analysis rows /
24 371 attachment rows, one user.

Two output formats, one dataset:

  --format sql      multi-row INSERTs. Feeds both PostgreSQL (psql) and
                    spg (spg import) — no generate_series, no COPY.
  --format ndjson   records for `mailrs-fastcore-migrate`, which replays
                    them through `deliver_message` — the same call the
                    real ingest path uses, so the kevy side derives its
                    thread aggregates and per-user rows itself rather
                    than having them handed over pre-computed.

Both formats read the *same* generated rows, so the three benchmark arms
(pg / spg / fastcore) compare equal amounts of work. That is the point:
a comparison across arms fed by two independently generated datasets is
a comparison of two datasets.

Note for anyone reading old numbers: the `email_analysis` categories now
come from a pre-pass keyed by message id, so both formats can carry the
same category per message. That changed which categories the SQL output
emits, so pg/spg figures recorded before 2026-08-13 were taken against a
different dataset and do not belong in a table beside these.

Usage:
  bench-api-seed.py > seed.sql
  bench-api-seed.py --format ndjson > seed.ndjson
"""

import argparse
import json
import random
import sys

MESSAGES = 24_304
THREADS = 23_508
ANALYSIS = 6_263
ATTACHMENTS = 24_371
BATCH = 500

DOMAIN = "bench.local"
ADDRESS = "bench@bench.local"
# argon2id of "bench-password", fixed salt — matches users.rs verify_hash
HASH = "$argon2id$v=19$m=19456,t=2,p=1$YmVuY2hzYWx0YmVuY2hzYWx0$aTmjX/qlKnp01PFBFtErHl76zMHz65r0mifk1CAgQZQ"

WORDS = (
    "invoice meeting schedule report deadline budget review contract "
    "shipment quarterly forecast renewal approval ticket deploy outage "
    "maintenance newsletter promotion receipt statement reminder agenda"
).split()

SENDERS = [f"sender{i}@example{i % 7}.com" for i in range(40)]
CATEGORIES = ["personal", "notification", "promotion", "general"]

BASE_EPOCH = 1_748_000_000  # 2025-05 — spread one minute apart

rng = random.Random(2026_06_12)

# Category per message id, generated up front so the SQL rows and the
# NDJSON records can carry the same one. Its own generator, so adding an
# output format never shifts the message stream underneath it.
cat_rng = random.Random(2026_06_13)
CATEGORY_BY_MID = {mid: cat_rng.choice(CATEGORIES) for mid in range(1, ANALYSIS + 1)}


def words(n: int) -> str:
    return " ".join(rng.choice(WORDS) for _ in range(n))


def q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def gen_messages():
    """Yield one dict per message, newest last.

    The single source of the dataset. Both emitters consume this, in this
    order, so neither can drift from the other.
    """
    for i in range(1, MESSAGES + 1):
        # First (MESSAGES - THREADS) rows pair up onto shared thread ids so
        # the distinct-thread count lands exactly on THREADS, like prod
        # (mostly single-message threads).
        thread_no = i if i > (MESSAGES - THREADS) * 2 else (i + 1) // 2
        sender = rng.choice(SENDERS)
        subject = words(5)
        body = words(300)  # ~2 KB, prod-ish text_body size
        clean = words(80)
        epoch = BASE_EPOCH + i * 60
        # flags bit 0 = \Seen. 20% arrive unread.
        seen = 0 if rng.random() < 0.2 else 1
        yield {
            "id": i,
            "uid": i,
            "maildir_id": f"maildir-{i}",
            "sender": sender,
            "subject": subject,
            "body": body,
            "clean": clean,
            "epoch": epoch,
            "flags": seen,
            "message_id": f"msg-{i}@example.com",
            "thread_id": f"thread-{thread_no}",
            "category": CATEGORY_BY_MID.get(i, "general"),
        }


# ── SQL ─────────────────────────────────────────────────────────────────

MSG_COLS = (
    "id, mailbox_id, uid, maildir_id, sender, recipients, subject,"
    " date_epoch, size, flags, internal_date, message_id, in_reply_to,"
    " thread_id, modseq, pinned, archived, text_body, html_body,"
    " clean_text, new_content, importance_level, importance_score,"
    " is_bulk_sender, has_tracking_pixel"
)


def emit_batch(table: str, cols: str, rows: list[str]) -> None:
    print(f"INSERT INTO {table} ({cols}) VALUES")
    print(",\n".join(rows) + ";")


def emit_sql() -> None:
    print("-- generated by scripts/bench-api-seed.py — deterministic, do not edit")
    print(f"INSERT INTO domains (name) VALUES ({q(DOMAIN)});")
    print(
        f"INSERT INTO accounts (address, domain, display_name, password_hash, active)"
        f" VALUES ({q(ADDRESS)}, {q(DOMAIN)}, 'Bench User', {q(HASH)}, true);"
    )
    print(
        "INSERT INTO mailboxes (user_address, name, uidvalidity, uidnext, highest_modseq)"
        f" VALUES ({q(ADDRESS)}, 'INBOX', 1, {MESSAGES + 1}, {MESSAGES});"
    )

    rows = []
    for m in gen_messages():
        rows.append(
            f"({m['id']}, 1, {m['uid']}, {q(m['maildir_id'])}, {q(m['sender'])},"
            f" {q(ADDRESS)}, {q(m['subject'])}, {m['epoch']}, 2048, {m['flags']},"
            f" {m['epoch']}, {q('<' + m['message_id'] + '>')}, '',"
            f" {q(m['thread_id'])}, {m['id']}, false, false, {q(m['body'])}, NULL,"
            f" {q(m['clean'])}, NULL, 'normal', 0.0, false, false)"
        )
        if len(rows) == BATCH:
            emit_batch("messages", MSG_COLS, rows)
            rows = []
    if rows:
        emit_batch("messages", MSG_COLS, rows)

    # no setval: the perf panel never inserts into the seeded tables, and
    # spg's BIGSERIAL doesn't expose an addressable <table>_id_seq (round-23
    # note filed). if this seed is ever reused for a write workload on PG,
    # bump the sequences first.

    for start in range(1, ANALYSIS + 1, BATCH):
        end = min(start + BATCH - 1, ANALYSIS)
        rows = [
            f"({mid}, {q(CATEGORY_BY_MID[mid])}, {rng.randrange(0, 30)}, '',"
            f" {q(words(12))}, '[]', '[]', '[]', '[]', '', {q(words(60))},"
            f" {'true' if rng.random() < 0.1 else 'false'}, NULL, 'inform')"
            for mid in range(start, end + 1)
        ]
        emit_batch(
            "email_analysis",
            "message_id, category, risk_score, risk_reason, summary, people,"
            " dates, amounts, action_items, model_version, clean_text,"
            " requires_action, action_deadline, sender_intent",
            rows,
        )

    rows = []
    for i in range(ATTACHMENTS):
        mid = (i % MESSAGES) + 1
        idx = i // MESSAGES
        rows.append(
            f"({mid}, {idx}, 'application/pdf', {q(words(40))}, 'en', 0.9, 1, '{{}}')"
        )
        if len(rows) == BATCH:
            emit_batch(
                "attachment_content",
                "message_id, attachment_index, content_type, extracted_text,"
                " language, ocr_confidence, page_count, metadata",
                rows,
            )
            rows = []
    if rows:
        emit_batch(
            "attachment_content",
            "message_id, attachment_index, content_type, extracted_text,"
            " language, ocr_confidence, page_count, metadata",
            rows,
        )


# ── NDJSON ──────────────────────────────────────────────────────────────


def emit_ndjson() -> None:
    """One account record, then one message record per message.

    Thread rows are deliberately NOT emitted. `deliver_message` derives the
    thread aggregate and the per-user membership row from the messages, and
    that is the path production takes — handing over pre-computed aggregates
    would measure a store loaded by a route no mail ever uses, and would let
    the aggregates disagree with the messages under them.
    """
    account = {
        "address": ADDRESS,
        "domain": DOMAIN,
        "display_name": "Bench User",
        "active": True,
        "created_at": BASE_EPOCH,
        "quota_bytes": 0,
        "password_hash": HASH,
    }
    print(json.dumps({"kind": "account", "blob": account}, separators=(",", ":")))

    for m in gen_messages():
        wire = {
            "id": 0,
            "mailbox_id": 0,
            "uid": m["uid"],
            "blob_ref": m["maildir_id"],
            "sender": m["sender"],
            "recipients": ADDRESS,
            "subject": m["subject"],
            "date": m["epoch"],
            "internal_date": m["epoch"],
            "size": 2048,
            "flags": m["flags"],
            "message_id": m["message_id"],
            "in_reply_to": "",
            "sender_trust": "",
            "thread_id": m["thread_id"],
            "modseq": m["id"],
            "user_address": ADDRESS,
        }
        print(
            json.dumps(
                {
                    "kind": "message",
                    "user": ADDRESS,
                    "thread_id": m["thread_id"],
                    "message_id": m["message_id"],
                    "internal_date": m["epoch"],
                    "category": m["category"],
                    # flags bit 0 = \Seen, so unread is its absence.
                    "unread": (m["flags"] & 1) == 0,
                    "wire": wire,
                },
                separators=(",", ":"),
            )
        )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--format", choices=("sql", "ndjson"), default="sql")
    args = ap.parse_args()

    if args.format == "sql":
        emit_sql()
    else:
        emit_ndjson()

    # The counts the harness asserts each arm reports back. On stderr so
    # they never land in the data stream.
    print(
        f"seed: format={args.format} messages={MESSAGES} threads={THREADS} "
        f"address={ADDRESS}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
