#!/usr/bin/env python3
"""Emit deterministic seed SQL for the e2e web-API perf baseline.

Shape mirrors the round-22 production dataset (2026-06-12 forensics):
24 304 messages / 23 508 distinct threads / 6 263 email_analysis rows /
24 371 attachment_content rows, one user. Output is plain multi-row
INSERTs (no generate_series, no COPY) so the same file feeds both
PostgreSQL (psql) and SPG (spg import).

Usage: bench-api-seed.py > seed.sql
"""

import random

MESSAGES = 24_304
THREADS = 23_508
ANALYSIS = 6_263
ATTACHMENTS = 24_371
BATCH = 500

DOMAIN = "bench.local"
ADDRESS = "bench@bench.local"
# argon2id of "bench-password", fixed salt — matches users.rs verify_hash
HASH = "$argon2id$v=19$m=19456,t=2,p=1$YmVuY2hzYWx0YmVuY2hzYWx0$aTmjX/qlKnp01PFBFtErHl76zMHz65r0mifk1CAgQZQ"

WORDS = (
    "invoice meeting schedule report deadline budget review contract "
    "shipment quarterly forecast renewal approval ticket deploy outage "
    "maintenance newsletter promotion receipt statement reminder agenda"
).split()

SENDERS = [f"sender{i}@example{i % 7}.com" for i in range(40)]
CATEGORIES = ["personal", "notification", "promotion", "general"]

rng = random.Random(2026_06_12)


def words(n: int) -> str:
    return " ".join(rng.choice(WORDS) for _ in range(n))


def q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def emit_batch(table: str, cols: str, rows: list[str]) -> None:
    print(f"INSERT INTO {table} ({cols}) VALUES")
    print(",\n".join(rows) + ";")


print("-- generated by scripts/bench-api-seed.py — deterministic, do not edit")
print(f"INSERT INTO domains (name) VALUES ({q(DOMAIN)});")
print(
    f"INSERT INTO accounts (address, domain, display_name, password_hash, active)"
    f" VALUES ({q(ADDRESS)}, {q(DOMAIN)}, 'Bench User', {q(HASH)}, true);"
)
print(
    "INSERT INTO mailboxes (user_address, name, uidvalidity, uidnext, highest_modseq)"
    f" VALUES ({q(ADDRESS)}, 'INBOX', 1, {MESSAGES + 1}, {MESSAGES});"
)

# messages: ids 1..MESSAGES via explicit id so attachment/analysis FKs are
# stable. first (MESSAGES - THREADS) rows reuse thread ids pairwise so the
# distinct-thread count lands exactly on THREADS, like prod (mostly
# single-message threads).
BASE_EPOCH = 1_748_000_000  # 2025-05 — spread one minute apart
rows = []
for i in range(1, MESSAGES + 1):
    thread_no = i if i > (MESSAGES - THREADS) * 2 else (i + 1) // 2
    sender = rng.choice(SENDERS)
    subject = words(5)
    body = words(300)  # ~2 KB, prod-ish text_body size
    clean = words(80)
    epoch = BASE_EPOCH + i * 60
    unseen = 0 if rng.random() < 0.2 else 1  # flags bit 0 = \Seen
    rows.append(
        f"({i}, 1, {i}, {q(f'maildir-{i}')}, {q(sender)}, {q(ADDRESS)},"
        f" {q(subject)}, {epoch}, 2048, {unseen}, {epoch},"
        f" {q(f'<msg-{i}@example.com>')}, '', {q(f'thread-{thread_no}')}, {i},"
        f" false, false, {q(body)}, NULL, {q(clean)}, NULL, 'normal', 0.0,"
        f" false, false)"
    )
    if len(rows) == BATCH:
        emit_batch(
            "messages",
            "id, mailbox_id, uid, maildir_id, sender, recipients, subject,"
            " date_epoch, size, flags, internal_date, message_id, in_reply_to,"
            " thread_id, modseq, pinned, archived, text_body, html_body,"
            " clean_text, new_content, importance_level, importance_score,"
            " is_bulk_sender, has_tracking_pixel",
            rows,
        )
        rows = []
if rows:
    emit_batch(
        "messages",
        "id, mailbox_id, uid, maildir_id, sender, recipients, subject,"
        " date_epoch, size, flags, internal_date, message_id, in_reply_to,"
        " thread_id, modseq, pinned, archived, text_body, html_body,"
        " clean_text, new_content, importance_level, importance_score,"
        " is_bulk_sender, has_tracking_pixel",
        rows,
    )
    rows = []

print(f"SELECT setval('messages_id_seq', {MESSAGES});")

# email_analysis: first ANALYSIS message ids
for start in range(1, ANALYSIS + 1, BATCH):
    end = min(start + BATCH - 1, ANALYSIS)
    rows = [
        f"({mid}, {q(rng.choice(CATEGORIES))}, {rng.randrange(0, 30)}, '',"
        f" {q(words(12))}, '[]', '[]', '[]', '[]', '', {q(words(60))},"
        f" {'true' if rng.random() < 0.1 else 'false'}, NULL, 'inform')"
        for mid in range(start, end + 1)
    ]
    emit_batch(
        "email_analysis",
        "message_id, category, risk_score, risk_reason, summary, people,"
        " dates, amounts, action_items, model_version, clean_text,"
        " requires_action, action_deadline, sender_intent",
        rows,
    )

# attachment_content: ATTACHMENTS rows distributed over messages (some get 2)
rows = []
for i in range(ATTACHMENTS):
    mid = (i % MESSAGES) + 1
    idx = i // MESSAGES
    rows.append(
        f"({mid}, {idx}, 'application/pdf', {q(words(40))}, 'en', 0.9, 1, '{{}}')"
    )
    if len(rows) == BATCH:
        emit_batch(
            "attachment_content",
            "message_id, attachment_index, content_type, extracted_text,"
            " language, ocr_confidence, page_count, metadata",
            rows,
        )
        rows = []
if rows:
    emit_batch(
        "attachment_content",
        "message_id, attachment_index, content_type, extracted_text,"
        " language, ocr_confidence, page_count, metadata",
        rows,
    )
