-- Brand data: update this file, then publish the rule bundle.
-- OpenAI domains: https://help.openai.com/en/articles/11725090-verifying-communications-from-openai
BRANDS = {
    {name = "chatgpt", domains = {"openai.com", "c-openai.com"}},
    {name = "openai", domains = {"openai.com", "c-openai.com"}},
    {name = "icloud", domains = {"apple.com", "icloud.com", "me.com"}},
    {name = "apple", domains = {"apple.com", "icloud.com", "itunes.com", "me.com"}},
    {name = "amazon", domains = {"amazon.com", "amazon.co.jp", "amazon.jp", "amazonses.com", "amazonaws.com", "aws.com"}},
    {name = "paypal", domains = {"paypal.com", "paypal.co.jp"}},
    {name = "netflix", domains = {"netflix.com"}},
    {name = "aeon", domains = {"aeon.co.jp", "aeon.com", "aeonbank.co.jp", "aeoncard.co.jp"}},
    {name = "american express", domains = {"americanexpress.com", "aexp.com"}},
    {name = "amex", domains = {"americanexpress.com", "aexp.com"}},
    {name = "ANAマイレージクラブ", domains = {"ana.co.jp", "anamile.jp"}},
    {name = "ANAカード", domains = {"ana.co.jp", "anamile.jp"}},
    {name = "アマゾン", domains = {"amazon.com", "amazon.co.jp", "amazon.jp"}},
    {name = "myjcb", domains = {"jcb.co.jp"}},
    {name = "セゾンカード", domains = {"saisoncard.co.jp"}},
    {name = "saison", domains = {"saisoncard.co.jp"}},
    {name = "三井住友カード", domains = {"smbc.co.jp", "smbc-card.com", "vpass.ne.jp"}},
    {name = "楽天カード", domains = {"rakuten.co.jp", "rakuten.com", "rakuten-card.co.jp"}},
    {name = "mufg", domains = {"mufg.jp", "bk.mufg.jp"}},
    {name = "smbc", domains = {"smbc.co.jp", "smbc-card.com"}},
    {name = "jcb", domains = {"jcb.co.jp"}},
    {name = "rakuten", domains = {"rakuten.co.jp", "rakuten.com", "rakuten-card.co.jp"}},
    {name = "etc利用照会", domains = {"etc-meisai.jp"}},
    {name = "sagawa", domains = {"sagawa-exp.co.jp"}},
    {name = "ヤマト運輸", domains = {"kuronekoyamato.co.jp"}},
}
SUBJECT_CLAIMS = {
    {name = "chatgpt", domains = {"openai.com", "c-openai.com"}},
    {name = "openai", domains = {"openai.com", "c-openai.com"}},
    {name = "ANAマイレージ", domains = {"ana.co.jp", "anamile.jp"}},
    {name = "ANAカード", domains = {"ana.co.jp", "anamile.jp"}},
    {name = "【ANA】", domains = {"ana.co.jp", "anamile.jp"}},
    {name = "MyJCB", domains = {"jcb.co.jp"}},
    {name = "【JCB", domains = {"jcb.co.jp"}},
    {name = "セゾンカード", domains = {"saisoncard.co.jp"}},
    {name = "【SAISON", domains = {"saisoncard.co.jp"}},
    {name = "【AEON", domains = {"aeon.co.jp", "aeonbank.co.jp", "aeoncard.co.jp", "aeon.com"}},
    {name = "【iAEON", domains = {"aeon.co.jp", "aeonbank.co.jp", "aeoncard.co.jp", "aeon.com"}},
    {name = "イオンカード", domains = {"aeon.co.jp", "aeonbank.co.jp", "aeoncard.co.jp"}},
    {name = "楽天カード", domains = {"rakuten.co.jp", "rakuten.com", "rakuten-card.co.jp"}},
    {name = "三井住友", domains = {"smbc.co.jp", "smbc-card.com", "vpass.ne.jp"}},
    {name = "【SMBC", domains = {"smbc.co.jp", "smbc-card.com", "vpass.ne.jp"}},
    {name = "AppleID", domains = {"apple.com", "icloud.com", "me.com"}},
    {name = "Apple ID", domains = {"apple.com", "icloud.com", "me.com"}},
    {name = "iCloud", domains = {"apple.com", "icloud.com", "me.com"}},
    {name = "ETC利用照会", domains = {"etc-meisai.jp"}},
    {name = "マイナポータル", domains = {"myna.go.jp", "digital.go.jp"}},
    {name = "Amazon", domains = {"amazon.com", "amazon.co.jp", "amazon.jp", "amazonses.com", "amazonaws.com", "aws.com", "audible.co.jp"}},
}
HOSTED_CLAIMS = {
    {name = "aliyun", domains = {"aliyun.com", "alibaba.com", "aliyuncs.com", "alibaba-inc.com"}},
    {name = "tencent", domains = {"tencent.com", "qq.com"}},
    {name = "amazon", domains = {"amazon.com", "amazon.co.jp", "amazonaws.com", "aws.com", "amazonses.com"}},
    {name = "google", domains = {"google.com", "gmail.com", "googlemail.com", "youtube.com"}},
    {name = "apple", domains = {"apple.com", "icloud.com", "me.com"}},
    {name = "icloud", domains = {"apple.com", "icloud.com"}},
    {name = "microsoft", domains = {"microsoft.com", "outlook.com", "office.com", "microsoftonline.com"}},
    {name = "paypal", domains = {"paypal.com"}},
    {name = "rakuten", domains = {"rakuten.co.jp", "rakuten.com"}},
    {name = "baidu", domains = {"baidu.com"}},
    {name = "netflix", domains = {"netflix.com"}},
    {name = "docomo", domains = {"docomo.ne.jp", "nttdocomo.co.jp"}},
    {name = "jcb", domains = {"jcb.co.jp"}},
    {name = "line", domains = {"line.me", "linecorp.com"}},
}
